import pyvisa
RM = pyvisa.ResourceManager()
RM.list_resources()
SMU = RM.open_resource('USB0::0x0957::0x8B18::MY51143520::INSTR')
SMU.write("*RST")
SMU.write('sour:func:mode curr')
SMU.write('sour:func:shap puls')
SMU.write('sour:curr:mode sweep')
SMU.write('sour:curr:star 0')
SMU.write('sour:curr:stop 2')
SMU.write('sour:curr:step 0.05')
SMU.write('puls:del 1E-04')
SMU.write('puls:widt 1E-04')
SMU.write('sens:volt:aper 1E-04')
SMU.write('sens:volt:auto on')
SMU.write('sens:rem on')
SMU.write('outp:filt off')
SMU.write('outp:off:auto on')
SMU.write('outp on')
SMU.write('init (@1)')

