import pyvisa
import numpy as np
import matplotlib.pyplot as plt
RM = pyvisa.ResourceManager()
RM.list_resources()
SMU = RM.open_resource('USB0::0x0957::0x8B18::MY51143520::INSTR')
SMU.write("*RST")
SMU.write("syst:lfr 60")
SMU.write('sour:func:mode curr')
SMU.write('sour:func:shap puls')
SMU.write('sour:puls:del 1E-04')
SMU.write('sour:puls:widt 1E-04')
SMU.write('sour:curr 0.0')
SMU.write('sens:rem on')
SMU.write('sens:volt:prot:pos 5')
SMU.write('form:elem:sens volt, curr')
values = []
SMU.write('outp on')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.05')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.10')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.15')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.20')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.25')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.30')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.35')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.40')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.45')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.50')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.55')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.60')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.65')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.70')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.75')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.80')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.85')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.90')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 0.95')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.00')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.05')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.10')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.15')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.20')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.25')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.30')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.35')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.40')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.45')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.50')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.55')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.60')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.65')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.70')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.75')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.80')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.85')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.90')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 1.95')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('sour:curr 2.00')
SMU.write('init (@1)')
values.append(SMU.query('fetc:arr?'))
SMU.write('outp off')
values = np.array(values)
np.savetxt('VoltCurrMeas.csv', values,fmt = '%s', delimiter=',', newline = '\n')
mydata = np.genfromtxt('VoltCurrMeas.csv', delimiter=',')
voltage = mydata[:,0]
current = mydata[:,1]
plt.scatter(voltage, current)
plt.show()